search_for_retakes/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^search-retake/', include(('search_retake.urls', 'search_retake'), namespace='search_retake')),
    path('chaining/', include('smart_selects.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/search-retake/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

search_retake/urls.py
from django.urls import path
from .views import search_retake, get_disciplines, get_teachers, get_groups, RetakeListing


urlpatterns = [
    path('', search_retake, name='search_retake'),
    path('retake_listing', RetakeListing.as_view(), name='listing'),
    path('ajax/disciplines', get_disciplines, name='get_disciplines'),
    path('ajax/teachers', get_teachers, name='get_teachers'),
    path('ajax/groups', get_groups, name='get_groups'),
]

search_retake/models.py
from django.db import models
from django.core.exceptions import ValidationError

from smart_selects.db_fields import ChainedForeignKey


class Group(models.Model):
    COURSE_CHOICES = [
        (1, '1 курс'),
        (2, '2 курс'),
        (3, '3 курс'),
        (4, '4 курс'),
    ]

    course = models.IntegerField(choices=COURSE_CHOICES, verbose_name='Курс', help_text='Выберите курс')
    name = models.CharField(max_length=100, verbose_name='Название', help_text='Введите группу', unique=True)

    def __str__(self):
        return self.name


class Teacher(models.Model):
    name = models.CharField(max_length=40, verbose_name='Имя', help_text='Введите имя преподавателя')
    fathers_name = models.CharField(max_length=100, verbose_name='Отчество', help_text='Введите отчество преподавателя')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия', help_text='Введите фамилию преподавателя')

    def __str__(self):
        return f'{self.last_name} {self.name[0]}.{self.fathers_name[0]}.'

    def display_discipline(self):
        return ', '.join([discipline.name for discipline in self.disciplines.all()])

    display_discipline.short_description = 'Дисциплина'


class Discipline(models.Model):
    _SEMESTER_CHOICES = (
        (1, '1 семестр'),
        (2, '2 семестр'),
        (3, '3 семестр'),
        (4, '4 семестр'),
        (5, '5 семестр'),
        (6, '6 семестр'),
        (7, '7 семестр'),
        (8, '8 семестр')
    )

    _EXAM_TYPE = (
        (1, 'Зачет'),
        (2, 'Экзамен')
    )

    name = models.CharField(max_length=100, verbose_name='Название', help_text='Введите название дисциплины')
    semester = models.IntegerField(choices=_SEMESTER_CHOICES, verbose_name='Семестр', help_text='Выберите семестр')
    exam_type = models.IntegerField(choices=_EXAM_TYPE, verbose_name='Вид контроля', help_text='Выберите вид контроля')
    teachers = models.ManyToManyField(Teacher, related_name='disciplines', verbose_name='Преподаватели',
                                      help_text='Выберите преподавателей')

    def display_teacher(self):
        return ', '.join([teacher.__str__() for teacher in self.teachers.all()])

    display_teacher.short_description = 'Преподаватели'

    def __str__(self):
        return f'{self.name}, {self.semester} сем.'


class Retake(models.Model):
    discipline = models.ForeignKey(Discipline, verbose_name='Дисциплина', on_delete=models.CASCADE)
    teacher = ChainedForeignKey(
        Teacher,
        chained_field='discipline',
        chained_model_field='disciplines',
        verbose_name='Преподаватель',
    )
    group = models.ForeignKey(Group, verbose_name='Группа', on_delete=models.CASCADE)
    audience = models.CharField(max_length=5, verbose_name='Номер аудитории', help_text='Введите номер аудитории')
    date = models.DateTimeField(verbose_name='Дата', help_text='Введите дату пересдачи')

    def __str__(self):
        return f'{self.discipline.name}, {self.group.name}, {self.date}'

search_retake/forms.py
from django import forms

from .models import Group


class SearchForRetakeForm(forms.Form):
    course_choices = empty_choice = [('None', '---------'), ]
    course_choices += Group.COURSE_CHOICES

    courses = forms.ChoiceField(choices=course_choices)
    groups = forms.ModelChoiceField(queryset=Group.objects.all().filter(course=0))

    def __init__(self, course_id=None, *args, **kwargs):
        super().__init__(*args, **kwargs)

        groups = forms.ModelChoiceField(queryset=Group.objects.all().filter(course=course_id))

search_retake/views.py
from django.shortcuts import render
from django.http import JsonResponse
from rest_framework.generics import ListAPIView

from .pagination import StandardResultsSetPagination
from .serializers import RetakeSerializers
from .models import Retake, Discipline, Teacher, Group


def search_retake(request):
    return render(request, 'search_retake.html')


class RetakeListing(ListAPIView):
    pagination_class = StandardResultsSetPagination
    serializer_class = RetakeSerializers

    def get_queryset(self):
        query_list = Retake.objects.all()

        discipline = self.request.query_params.get('discipline', None)
        teacher = self.request.query_params.get('teacher', None)
        course = self.request.query_params.get('course', None)
        group = self.request.query_params.get('group', None)

        if discipline:
            query_list = query_list.filter(discipline=discipline)
            print(query_list, '\n\n\n')
        if teacher:
            query_list = query_list.filter(teacher=teacher)
        if course:
            query_list = query_list.filter(group__course=course)
        if group:
            query_list = query_list.filter(group=group)
        return query_list


def get_disciplines(request):
    if request.is_ajax and request.method == 'GET':
        discipline_ids = Retake.objects.order_by('discipline').values_list('discipline').distinct()
        disciplines = [(i[0], str(Discipline.objects.get(id=i[0]))) for i in list(discipline_ids)]
        data = {
            'disciplines': disciplines,
        }
        return JsonResponse(data, status=200)


def get_teachers(request):
    if request.is_ajax and request.method == 'GET':
        discipline = request.GET.get('discipline')
        teacher_ids = Retake.objects.filter(discipline=discipline).order_by('teacher').values_list('teacher').distinct()
        teachers = [(i[0], str(Teacher.objects.get(id=i[0]))) for i in list(teacher_ids)]
        data = {
            'teachers': teachers,
        }
        return JsonResponse(data, status=200)


def get_groups(request):
    if request.is_ajax and request.method == 'GET':
        course = request.GET.get('course')
        groups = Retake.objects.filter(group__course=course).order_by('group').values_list('group').distinct()
        groups = [(i[0], str(Group.objects.get(id=i[0]))) for i in list(groups)]
        data = {
            'groups': groups,
        }
        return JsonResponse(data, status=200)

search_retake/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon -->
    {% load static %}
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'img/favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'img/favicon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'img/favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'img/favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'img/favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% block stylesheet %}
    {% endblock %}

    <title>Отслеживание пересдач</title>
</head>
<body>
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}
</body>
</html>

search_retake/templates/search_retake.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}
    <header class="text-center">
        <h1 class="h1">Поиск пересдач</h1>
    </header>
    <main class="container">
        <form id="FindRetakesForm" method="GET" action="">
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="discipline">Дисциплина</label>
                    <select class="form-control" name="discipline" id="discipline"
                    url = "{% url 'search_retake:get_disciplines' %}">
                    </select>
                </div>
                <div class="form-group col-md-3">
                    <label for="teacher">Преподаватель</label>
                    <select class="form-control" name="teacher" id="teacher"
                    url="{% url 'search_retake:get_teachers' %}" disabled>
                        <option value="_None">---------</option>
                    </select>
                </div>
                <div class="form-group col-md-2">
                    <label for="course">Курс</label>
                    <select name="course" id="course" class="form-control">
                        <option value="_None">---------</option>
                        <option value="1">1 Курс</option>
                        <option value="2">2 Курс</option>
                        <option value="3">3 Курс</option>
                        <option value="4">4 Курс</option>
                    </select>
                </div>
                <div class="form-group col-md-3">
                    <label for="group">Группа</label>
                    <select class="form-control" name="group" id="group"
                    url="{% url 'search_retake:get_groups' %}" disabled>
                        <option value="_None">---------</option>
                    </select>
                </div>
            </div>
        </form>
        <div id="no_result" class="text-center">
            <h5 class="h5">Пересдач нет</h5>
        </div>
        <table id="list_data" class="table table-bordered table-hover table-striped" data-toggle="table"
        url="{% url 'search_retake:listing' %}">
            <thead>
                <tr>
                    <th scope="col" data-field="discipline">Дисциплина</th>
                    <th scope="col" data-field="teacher">Преподаватель</th>
                    <th scope="col" data-field="group">Группа</th>
                    <th scope="col" data-field="audience">Аудитория</th>
                    <th scope="col" data-field="date">Дата</th>
                </tr>
            </thead>
            <tbody id="listing">
            </tbody>
        </table>
        <div class="row justify-content-center">
            <nav aria-label="navigation">
                    <ul class="pagination">
                        <li class="page-item">
                            <button class="btn btn-primary page-link" id="previous"><</button>
                        </li>
                        <li class="page-item pull-right">
                            <button class="btn btn-primary page-link" id="next">></button>
                        </li>
                    </ul>
                </nav>
        </div>
    </main>
{% endblock %}
{% block script %}
    <script src="{% static 'js/search-retake.js' %}"></script>
{% endblock %}